apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 646437910396-3s7f5pps9779clrj8hj33oalq4irmitu.apps.googleusercontent.com
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: https://72.61.224.87.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
