apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini
  namespace: gemini-namespace
  labels:
    app: gemini
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gemini
  template:
    metadata:
      labels:
        app: gemini
    spec:
      containers:
      - name: gemini
        image: vishalchauhan1830/gemininip:v2
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: GOOGLE_ID
          valueFrom:
            configMapKeyRef:
              name: gemini-config
              key: GOOGLE_ID
        - name: GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: GOOGLE_SECRET
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: gemini-config
              key: MONGODB_URI
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: NEXTAUTH_SECRET
        - name: NEXT_PUBLIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: NEXT_PUBLIC_API_KEY
              
        - name: HOSTNAME
          value: "0.0.0.0"
          
        - name: PORT
          value: "3000"
          
        - name: NODE_ENV
          value: "production"
          
        - name: NEXTAUTH_URL
          value: "http://187.127.154.185.nip.io:8080"

        - name: NEXTAUTH_URL_INTERNAL
          value: "http://localhost:3000"

        - name: TRUST_PROXY
          value: "true"
