apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLUNwSU1oZl9KRTU2N3ZUT0pYOHdRRnVOaWdxMF8= # Base64 for google key
  NEXTAUTH_SECRET: 3JarZ/ih/XHnK1JOFFQipXJ3+Sc9mUqUIdeAXLJN3y8= # Base64 for auth key
  NEXT_PUBLIC_API_KEY: QUl6YVN5Qzc3Qmg5ZWhxQkRnUDVoNWdaZGlVQVk1Rl9ERzJPVmE0 # Base64 for api key
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==  # Base64 for admin@123
