apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  #GOOGLE_ID: MTQwOTM1NzU3MTM0LTVkajVjdDdkNmtuamthdjE0Y2R2dDNpNXBwZXE2b2x2LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_API_KEY: QUl6YVN5QnpfWjNfZDdFQ1JlZXllVFphWGp5ZUd6MGJSVm1sLXFB
  GOOGLE_SECRET: R09DU1BYLUZwX0FhbXJ3YzN1Y29PQWZUb0ZCOHhKRExMYUo= # Base64 for google key
  NEXTAUTH_SECRET: M2JhMzg4NjUzMDAxZDNlNjVlNmFjOTBkOTczMDE4MTM5ZWVlMTdhZDYyZmU4YmViYmI3YzVkYzEzOTc5NGJkZg== # Base64 for auth key
  #NEXTAUTH_URL: aHR0cDovLzE4Ny4xMjcuMTU0LjE4NS5uaXAuaW86ODA4MA==
  #NEXTAUTH_URL: http://187.127.154.185.nip.io:8080
  NEXT_PUBLIC_API_KEY: QUl6YVN5QnpfWjNfZDdFQ1JlZXllVFphWGp5ZUd6MGJSVm1sLXFB # Base64 for api key
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==  # Base64 for admin@123
