apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLWlPZEcyQlh3TDZESTlmWDFFVUZIMTM5Q3VvejA= # Base64 for google key
  NEXTAUTH_SECRET: 3ba388653001d3e65e6ac90d973018139eee17ad62fe8bebbb7c5dc139794bdf # Base64 for auth key
  NEXT_PUBLIC_API_KEY: QUl6YVN5RDBsOU9kMGZ1WlJucHRnaTU3clR5dlNGQ0xSQXp3V1RZ # Base64 for api key
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==  # Base64 for admin@123
